Kmatrix:
  func: jitter.resonances.KmatX
  expects:
    - channels: 
      - chanel1:
        - m1: real
        - m2: real
        - index: const 0
        - bg: real
      - chanel2:
        - m1: real
        - m2: real
        - index: const 1
        - bg: real
    - alphas: 
      - a1: complex(real,real)
      - a2: complex(real,real)
    - resonances:
      - pole1:
        - pole mass: real
        - g: list[real]
      - pole2:
        - pole mass: real
        - g: list[real]
    - sigma: data
    - L: const 2
    - index: const 0
    
D2300:
  func: jitter.resonances.BWresonance
  expects: 
    - sigma: data
    - m: real
    - width: real