K:
  mass: 493.677
  spin: 0
  parity: -1
  type: meson

D0:
  mass: 1864.84
  spin: 0
  parity: -1
  type: meson

Lc:
  mass : 2286.46
  spin: 1
  parity: 1
  type: baryon

Lb:
  mass: 5619.60
  spin: 1
  parity: 1
  type: baryon

B:
  mass: 5279.65
  spin: 0
  parity: -1
  type: meson

Psi2S:
  mass: 3686.10
  spin: 2
  parity: -1
  type: meson

Pi:
  mass: 139.57
  spin: 0
  parity: -1
  type: meson

Bs:
  mass: 5368.0
  spin: 0
  parity: -1
  type: meson

p:
  mass: 938.27
  spin: 1
  parity: 1
  type: baryon

mu:
  mass: 105.658
  spin: 1
  parity: 1
  type: lepton

JPsi:
  mass: 3096.0
  spin: 2
  parity: -1
  type: meson